WINDOW_HEIGHT = 800
WINDOW_WIDTH = 800

OFFSET_VERTICAL = 50
OFFSET_HORIZONTAL = 50

BORDER_WIDTH = 10

PLAY_AREA_WIDTH = 700
PLAY_AREA_HEIGHT = 520

BLOCK_SIZE = 20
SNAKE_SIZE = BLOCK_SIZE // 1.1
SNAKE_GAP = (BLOCK_SIZE - SNAKE_SIZE) // 2
